version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: ${PG_CONTAINER}
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD} 
      POSTGRES_DB: ${DB_NAME}
      TZ: America/Sao_Paulo
    ports:
      - "${BIND_HOST:-127.0.0.1}:${DB_PORT:-5432}:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:4.2-management
    container_name: ${RABBITMQ_CONTAINER:-app_rabbitmq}
    hostname: app-rabbit
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    ports:
      - "${BIND_HOST:-127.0.0.1}:5672:5672"   # Porta do protocolo AMQP
      - "${BIND_HOST:-127.0.0.1}:15672:15672" # Porta do painel de gerência (UI)
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    restart: unless-stopped

volumes:
  pg_data:
  rabbitmq_data: